version: "3"

services:
  app:
    build: .
    command: 
      - python manage.py runserver 0:8000
      - python manage.py migrate
      - python db_uploader.py
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app 
    depends_on:
      - db
  db:
    image: mysql:8.0
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE: projectA
      - MYSQL_ROOT_PASSWORD: 1234